### ISSUE TITLE
Ink does not see plugins

### ISSUE THREAD

**Issue by drallgood** [octopress/ink#38]
I've put all the plugins in the Gemfile like this:
```
group :jekyll_plugins do
    gem 'octopress-feeds'
end
```

However `octopress ink list` does not recognize them:
```
Octopress Ink - v1.0.0.rc.30
You have no plugins installed.
```

**Comment by imathis** [comment]
Have you tried `bundle exec octopress ink list`?

**Comment by drallgood** [comment]
I did.. Same result.

**Comment by imathis** [comment]
I believe I've found the issue. I just released a new version of Octopress Ink that should fix this for you. Update and let me know if it is still an issue. Thanks!

**Comment by drallgood** [comment]
No dice.

```
$ bundle exec octopress ink list 
Octopress Ink - v1.0.0.rc.31
You have no plugins installed.
$ octopress ink list 
Octopress Ink - v1.0.0.rc.31
You have no plugins installed.
```

**Comment by drallgood** [comment]
This is very weird!
Don't know what I did, but now I get this instead:
```
bundle exec octopress ink list -t
/Library/Ruby/Gems/2.0.0/gems/octopress-date-format-3.0.2/lib/octopress-date-format.rb:78:in `format_date': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by imathis** [comment]
Well that's interesting. I don't think that date-format bug is related, but I'll see what I can figure out. Thanks for helping with this.

**Comment by drallgood** [comment]
Even if I remove the feeds plugin, the only plugin showing up is the assets pipeline.

I'm gonna try this on another Mac in a few minutes. This whole thing feels like something is being cached or something like that...

**Comment by imathis** [comment]
I've tracked down the plugin requiring issue and fixed it in the Octopress gem. If you run bundle update, the plugins listing issue should be fixed. I'm not sure what the deal is with date-format. Update and let me know if you're still having trouble with the date-format plugin.

**Comment by drallgood** [comment]
No idea what the deal is with the date-format plugin (looks like it can't find the config???) or the pullquote-tag plugin for that matter, but if I comment those two out, I still don't get the result I'm expecting:
```
$ bundle exec octopress ink list -t
Octopress Ink - v1.0.0.rc.32
 Octopress Asset Pipeline (octopress-asset-pipeline) - v2.0.0 - Combine and compress Stylesheets and Javascripts into a single fingerprinted file.
```
Here's the Gemfile:
```
group :jekyll_plugins, :octopress do
  gem "jekyll-compass", "~> 1.0.5"
  gem 'octopress-multilingual'
  gem 'octopress-quote-tag'
  gem 'octopress-asset-pipeline'
  gem 'octopress-codeblock'
  gem 'octopress-gist'
  gem 'octopress-codefence'
  gem 'octopress-return-tag'
  gem 'octopress-filters'
  gem 'octopress-linkblog'
end
```

I gave this a try on another Mac (clean install) and got exactly the same result.

**Comment by imathis** [comment]
Just so you know, the `list` subcommand will only show plugins that are built on Octopress Ink and use its features. Most of these are regular Jekyll plugins. The only one in this list that matches that is `octopress-asset-pipeline`.

**Comment by drallgood** [comment]
Ah... Didn't know that!

Good. Then I guess this issue is resolved. I'll open separate ones for the other issues I'm having.

Thanks!

**Comment by imathis** [comment]
@drallgood Thanks. I'm not sure what the issue is with the date-format or pullquote-tag. I'm trying but I can't seem to replicate it. Perhaps now that this one is out of the way, you can help me replicate it in those new issues.
